notifications:
  email: false
language: node_js
os:
- linux
- osx
node_js:
- '5.1'
sudo: false
script:
- npm install
addons:
  apt:
    packages:
    - libavahi-compat-libdnssd-dev

before_deploy:
- scripts/travis/before_deploy.sh
deploy:
  provider: releases
  api_key:
    secure: HTyVIZ5UCMEcRlTP4UhMebHkR1OeTwXxs9UBtHwORFTFYJ5YwX/KkZBesUbgWgZ1/MFCdoL47VXdbQRrchwdHFoq0rg47G9a8EKrTUG1GV+ISWRaAu3N/aEU4ZnjjFLgQfl6Mkwgrutn/D2D3hZ7/RLAmEn15cta/t8Ye2RWhtYeLhvN8oPPYNWyTP4X6yO5sZ5B6yboe2yJj5SRF/gxTBmLoJOqdJdms6hzPFhXI03zXlqfQZChq/BtptPtvHkF9GcFTRw106TVSvCWFsj339Q00+q1ijT0GtG8BheMaNRrtKFIAvyCUYUjOlWCJdy7TfqH7B/T2o7KNbsf+dMT1JNQCZRqoH3z2abomgIqoXMcbbMqcSsjbgUByGQcB2C/hBLQeMQ+M+RCNgSqiHQPaGXc6CRalvU+XF2F6NwFZz2SLrmNfx347KKmNV6htfiSS3//Vr3BRSDvTstw3hmEb3ES9DZflR/gbrb9GJZ8iH1K8p9gNJ82ikvpavfo8803w2rWpGPrCuXPnY98tErixc3rGf99Ijh4Ypy25FRy5bjBZAryxDHkeNrAqFjM/XOEA64zw83WRc+d7yQj5C601dGM8jiZwjEbsRGG7iv1gegG71vDRG+KSJksdDuhTBrJvBWnwY67kCqmAEeEDcTxa5klB1F9oaA7+rZak4QeoQk=
  file: ${HOME}/build/${TRAVIS_REPO_SLUG}/target/kibana_*_all.deb
  file: dist/HuxleyFM-*.*
  skip_cleanup: true
  on:
#    repo: jgrowl/huxleyfm
    tags: true
