notifications:
  email: false
language: node_js
os:
- linux
- osx
node_js:
- '5.1'
sudo: false
before_script:
  - "export DISPLAY=:99.0"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - sleep 3 # give xvfb some time to start
cache:
- apt: true
- directories:
  - "$HOME/.npm"
  - "$HOME/.electron"
  - "/Library/Caches/Homebrew"
addons:
  apt:
    packages:
    - libavahi-compat-libdnssd-dev
    - wine
before_deploy:
- scripts/travis/before_deploy.sh
deploy:
  provider: releases
  api_key:
    secure: IDZuMFpHYJiumnqrL9TRRHIAN9a45d4A6XRyEBQnutIQaQNBpI3gv8dMGi9Wub52gw/b9aKxV5QuR9iPuWbi/PJuRO6oxXpTjuMLx/Pf03OXl4itFp3y7GTUW2I2z7X5Mp6j9Tq7mCyW58J7lkIqDgdJW/BeVq/15cikCOFPq/CutMMwH3Td60LlwBjrAIU3E7yWPca1VG33i6NDMD7PAMKpVIQ3fUyBmMncSQ5q0s7s+twrxeirlsThUg96EgzG51qU8l+5jEU2yWwUtbd5JAhtKMonmCZ0+jBs18ePUBFaYP7Mavdbs3Eww/oipZsg1zLQfsc2agL8KYpY91/zhrs+mEVVdSPJNSA0hwnCDBACfKmskpDneuVygcwRzuDAFLUBt0p4ZLJJD5ZFSdjdZCkEmXZGeyIA589YZg2+AqQyrUH61TQTalGMzpjQQ9eq5rVYtSN3oNk49UDDZKREmdEcpNbu0JqMXTqqevPvfDjqE3o06EdwZvTlXOQeIj1B2IuZee1amxNTnpwJP5BcRfhK+iCK1XrTB4juMfz20cC75WkRhL5FB27g6Ekc8hK3V05fMhcDQX0tsM2W2vKxxifVU9IZ1wEddqC+HePQXx+9gA9YcpVWXORrTmcV+dJ6sDfryiQ9gaNZqRWKxCQsvynSFKoDluV2lEKOoz7yYac=
  file: dist/HuxleyFM-*.*
  file_glob: true
  skip_cleanup: true
  on:
    repo: cheshire137/huxleyfm
    tags: true
